### DISCUSSION TITLE
GPU driver issues on Vertex AI

### DISCUSSION THREAD

**Discussion by abhishek-ranjan-kindred** [getindata/kedro-vertexai#97] [Q&A] [answered]
I am running a simple Kedro pipeline on Vertex AI with a single node requiring a GPU. I modified the autogenerated config  `conf/base/vertexai.yml` resources as follows:
```
  resources:

    # Default settings for the nodes
    __default__:
      nvidia.com/gpu: 1
```
But the run fails with this error:  `*** failed with error: Found no NVIDIA driver on your system.  Please check that you have an NVIDIA  GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

Questions:
1. Do these drivers need to be installed somewhere or does it come pre-installed in the "pod" that Vertex AI uses?
2. Is there a specific base container needed to run nodes with GPU? My container builds on `FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04` .
